//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2010.02.23 at 11:10:13 AM MST 
//


package gov.utah.dts.det.ccl.logging;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
* <p>Java class for Application complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="Application">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="Username" type="{http://www.w3.org/2001/XMLSchema}token"/>
*         &lt;element name="SecureToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Application", propOrder = {
 "username",
 "secureToken"
})
public class Application {

 @XmlElement(name = "Username", required = true, namespace = "http://dts.utah.gov/alm/webservice/model")
 @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
 @XmlSchemaType(name = "token")
 protected String username;
 @XmlElement(name = "SecureToken", required = true, namespace = "http://dts.utah.gov/alm/webservice/model")
 protected String secureToken;

 /**
  * Gets the value of the username property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getUsername() {
     return username;
 }

 /**
  * Sets the value of the username property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setUsername(String value) {
     this.username = value;
 }

 /**
  * Gets the value of the secureToken property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getSecureToken() {
     return secureToken;
 }

 /**
  * Sets the value of the secureToken property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setSecureToken(String value) {
     this.secureToken = value;
 }

}