//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2010.02.23 at 11:10:13 AM MST 
//


package gov.utah.dts.det.ccl.logging;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for ResponseMessage complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="ResponseMessage">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="ResponseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="ResponseDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseMessage", propOrder = {
 "responseCode",
 "responseDescription"
})
public class ResponseMessage {

 @XmlElement(name = "ResponseCode", required = true)
 protected String responseCode;
 @XmlElement(name = "ResponseDescription", required = true)
 protected String responseDescription;

 /**
  * Gets the value of the responseCode property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getResponseCode() {
     return responseCode;
 }

 /**
  * Sets the value of the responseCode property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setResponseCode(String value) {
     this.responseCode = value;
 }

 /**
  * Gets the value of the responseDescription property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getResponseDescription() {
     return responseDescription;
 }

 /**
  * Sets the value of the responseDescription property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setResponseDescription(String value) {
     this.responseDescription = value;
 }

}